---
- name: Deploy AAP instance on OpenShift
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ openshift_api_server }}"
      api_key: "{{ openshift_token }}"
      validate_certs: "{{ openshift_validate_certs | bool }}"
  tasks:
    - name: Run AAP instance deploy role
      ansible.builtin.import_role:
        name: aap_instance
        tasks_from: deploy_instance
